FROM public.ecr.aws/docker/library/node:18.19.0-slim
# FROM node:18.19.0-slim

RUN mkdir /opt/app
COPY ../src/node_modules /opt/app/node_modules
COPY ../src/dist /opt/app/dist

WORKDIR /opt/app

ENTRYPOINT ["node", "dist/main.js"]
